//order create constants
export const ORDER_CREATE_REQUEST = 'ORDER_CREATE_REQUEST';
export const ORDER_CREATE_SUCCESS = 'ORDER_CREATE_SUCCESS';
export const ORDER_CREATE_FAIL = 'ORDER_CREATE_FAIL';
export const ORDER_CREATE_RESET = 'ORDER_CREATE_RESET';

// details of a single order
export const ORDER_DETAILS_REQUEST = 'ORDER_DETAILS_REQUEST';
export const ORDER_DETAILS_SUCCESS = 'ORDER_DETAILS_SUCCESS';
export const ORDER_DETAILS_FAIL = 'ORDER_DETAILS_FAIL';

// order payment constants
export const ORDER_PAY_REQUEST = 'ORDER_PAY_REQUEST';
export const ORDER_PAY_SUCCESS = 'ORDER_PAY_SUCCESS';
export const ORDER_PAY_FAIL = 'ORDER_PAY_FAIL';
export const ORDER_PAY_RESET ='ORDER_PAY_RESET';

// list a single users's orders 
export const LIST_MY_ORDER_REQUEST = 'LIST_MY_ORDER_REQUEST';
export const LIST_MY_ORDER_SUCCESS = 'LIST_MY_ORDER_SUCCESS';
export const LIST_MY_ORDER_FAIL = 'LIST_MY_ORDER_FAIL';
export const LIST_MY_ORDER_RESET = 'LIST_MY_ORDER_RESET';